=== mpozdeev/learn_xml_json/src/main/resources/run_schema2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:attribute name="name" type="xs:string"/>
    <xs:element name="shop">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="category" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="category">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="subcategory" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="subcategory">
        <xs:complexType>
            <xs:sequence>

            </xs:sequence>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== mpozdeev/learn_xml_json/src/main/resources/product2.xml
<?xml version="1.0" encoding="UTF-8"?>
<shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="run_schema2.xsd">
    <category name="clothes">
        <subcategory name="trousers"/>
        <subcategory name="shorts"/>
        <subcategory name="t-shirt"/>
    </category>
    <category name="shoes">
        <subcategory name="street"/>
        <subcategory name="rugged_terrain"/>

    </category>
</shop>
